### ISSUE TITLE
I forked your project

### ISSUE THREAD

**Issue by tommot348** [lepinay/elm-brackets#4]
Hi there, I forked your elm-brackets project and am developing it further.  
Is it possible that you remove your old stuff from the brackets extension registry, since it does not work on linux/mac?  
Would you mind linking to my repository (https://github.com/tommot348/elm-brackets) in your readme, so that users that want to do elm stuff with brackets will find it?

**Comment by lepinay** [comment]
Hi @tommot348, thanks for taking back this project to life again ;)

I've deleted my entry in the bracket extension registry and linked my repo to yours in my readme file.

**Comment by tommot348** [comment]
Wow thanks a lot!
